apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-voting-app
  namespace: kcdsp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-voting-app
  template:
    metadata:
      labels:
        app: nodejs-voting-app
    spec:
      containers:
      - name: nodejs-voting-app
        image: ghcr.io/yuriolisa/nodejs-voting-app:2.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-voting-app-service
  namespace: kcdsp
spec:
  type: ClusterIP
  selector:
    app: nodejs-voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
